/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { TranslateRequest } from '../model';
// @ts-ignore
import type { TranslateResult } from '../model';
/**
 * AdminTranslateApi - axios parameter creator
 * @export
 */
export const AdminTranslateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {TranslateRequest} translateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        translateLetter: async (translateRequest: TranslateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'translateRequest' is not null or undefined
            assertParamExists('translateLetter', 'translateRequest', translateRequest)
            const localVarPath = `/translate/translateLetter/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(translateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminTranslateApi - functional programming interface
 * @export
 */
export const AdminTranslateApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminTranslateApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {TranslateRequest} translateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async translateLetter(translateRequest: TranslateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TranslateResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.translateLetter(translateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminTranslateApi.translateLetter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminTranslateApi - factory interface
 * @export
 */
export const AdminTranslateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminTranslateApiFp(configuration)
    return {
        /**
         * 
         * @param {TranslateRequest} translateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        translateLetter(translateRequest: TranslateRequest, options?: RawAxiosRequestConfig): AxiosPromise<TranslateResult> {
            return localVarFp.translateLetter(translateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminTranslateApi - object-oriented interface
 * @export
 * @class AdminTranslateApi
 * @extends {BaseAPI}
 */
export class AdminTranslateApi extends BaseAPI {
    /**
     * 
     * @param {TranslateRequest} translateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminTranslateApi
     */
    public translateLetter(translateRequest: TranslateRequest, options?: RawAxiosRequestConfig) {
        return AdminTranslateApiFp(this.configuration).translateLetter(translateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

