/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddPersonRequest } from '../model';
// @ts-ignore
import type { CombinePersonRequest } from '../model';
// @ts-ignore
import type { CombinePersonResult } from '../model';
// @ts-ignore
import type { DeletePersonRequest } from '../model';
// @ts-ignore
import type { PeopleRequest } from '../model';
// @ts-ignore
import type { PeopleResult } from '../model';
// @ts-ignore
import type { PersonResult } from '../model';
// @ts-ignore
import type { UpdatePersonRequest } from '../model';
/**
 * AdminPersonApi - axios parameter creator
 * @export
 */
export const AdminPersonApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {DeletePersonRequest} deletePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePerson: async (deletePersonRequest: DeletePersonRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deletePersonRequest' is not null or undefined
            assertParamExists('deletePerson', 'deletePersonRequest', deletePersonRequest)
            const localVarPath = `/admin/deletePerson/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deletePersonRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CombinePersonRequest} combinePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCombinePerson: async (combinePersonRequest: CombinePersonRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'combinePersonRequest' is not null or undefined
            assertParamExists('getCombinePerson', 'combinePersonRequest', combinePersonRequest)
            const localVarPath = `/admin/getCombinePerson/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(combinePersonRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PeopleRequest} peopleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPersonsForIds: async (peopleRequest: PeopleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'peopleRequest' is not null or undefined
            assertParamExists('getPersonsForIds', 'peopleRequest', peopleRequest)
            const localVarPath = `/admin/getPersonsForIds/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(peopleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CombinePersonRequest} combinePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putCombinePerson: async (combinePersonRequest: CombinePersonRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'combinePersonRequest' is not null or undefined
            assertParamExists('putCombinePerson', 'combinePersonRequest', combinePersonRequest)
            const localVarPath = `/admin/putCombinePerson/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(combinePersonRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {AddPersonRequest} addPersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePerson: async (addPersonRequest: AddPersonRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addPersonRequest' is not null or undefined
            assertParamExists('updatePerson', 'addPersonRequest', addPersonRequest)
            const localVarPath = `/admin/updatePerson/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addPersonRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdatePersonRequest} updatePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePersonDetails: async (updatePersonRequest: UpdatePersonRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updatePersonRequest' is not null or undefined
            assertParamExists('updatePersonDetails', 'updatePersonRequest', updatePersonRequest)
            const localVarPath = `/admin/updatePersonDetails/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePersonRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminPersonApi - functional programming interface
 * @export
 */
export const AdminPersonApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminPersonApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {DeletePersonRequest} deletePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePerson(deletePersonRequest: DeletePersonRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePerson(deletePersonRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminPersonApi.deletePerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CombinePersonRequest} combinePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCombinePerson(combinePersonRequest: CombinePersonRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CombinePersonResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCombinePerson(combinePersonRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminPersonApi.getCombinePerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PeopleRequest} peopleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPersonsForIds(peopleRequest: PeopleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PeopleResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPersonsForIds(peopleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminPersonApi.getPersonsForIds']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CombinePersonRequest} combinePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putCombinePerson(combinePersonRequest: CombinePersonRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CombinePersonResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putCombinePerson(combinePersonRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminPersonApi.putCombinePerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {AddPersonRequest} addPersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePerson(addPersonRequest: AddPersonRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePerson(addPersonRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminPersonApi.updatePerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdatePersonRequest} updatePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePersonDetails(updatePersonRequest: UpdatePersonRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePersonDetails(updatePersonRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminPersonApi.updatePersonDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminPersonApi - factory interface
 * @export
 */
export const AdminPersonApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminPersonApiFp(configuration)
    return {
        /**
         * 
         * @param {DeletePersonRequest} deletePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePerson(deletePersonRequest: DeletePersonRequest, options?: RawAxiosRequestConfig): AxiosPromise<PersonResult> {
            return localVarFp.deletePerson(deletePersonRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CombinePersonRequest} combinePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCombinePerson(combinePersonRequest: CombinePersonRequest, options?: RawAxiosRequestConfig): AxiosPromise<CombinePersonResult> {
            return localVarFp.getCombinePerson(combinePersonRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PeopleRequest} peopleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPersonsForIds(peopleRequest: PeopleRequest, options?: RawAxiosRequestConfig): AxiosPromise<PeopleResult> {
            return localVarFp.getPersonsForIds(peopleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CombinePersonRequest} combinePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putCombinePerson(combinePersonRequest: CombinePersonRequest, options?: RawAxiosRequestConfig): AxiosPromise<CombinePersonResult> {
            return localVarFp.putCombinePerson(combinePersonRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AddPersonRequest} addPersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePerson(addPersonRequest: AddPersonRequest, options?: RawAxiosRequestConfig): AxiosPromise<PersonResult> {
            return localVarFp.updatePerson(addPersonRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdatePersonRequest} updatePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePersonDetails(updatePersonRequest: UpdatePersonRequest, options?: RawAxiosRequestConfig): AxiosPromise<PersonResult> {
            return localVarFp.updatePersonDetails(updatePersonRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminPersonApi - object-oriented interface
 * @export
 * @class AdminPersonApi
 * @extends {BaseAPI}
 */
export class AdminPersonApi extends BaseAPI {
    /**
     * 
     * @param {DeletePersonRequest} deletePersonRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminPersonApi
     */
    public deletePerson(deletePersonRequest: DeletePersonRequest, options?: RawAxiosRequestConfig) {
        return AdminPersonApiFp(this.configuration).deletePerson(deletePersonRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CombinePersonRequest} combinePersonRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminPersonApi
     */
    public getCombinePerson(combinePersonRequest: CombinePersonRequest, options?: RawAxiosRequestConfig) {
        return AdminPersonApiFp(this.configuration).getCombinePerson(combinePersonRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PeopleRequest} peopleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminPersonApi
     */
    public getPersonsForIds(peopleRequest: PeopleRequest, options?: RawAxiosRequestConfig) {
        return AdminPersonApiFp(this.configuration).getPersonsForIds(peopleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CombinePersonRequest} combinePersonRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminPersonApi
     */
    public putCombinePerson(combinePersonRequest: CombinePersonRequest, options?: RawAxiosRequestConfig) {
        return AdminPersonApiFp(this.configuration).putCombinePerson(combinePersonRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AddPersonRequest} addPersonRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminPersonApi
     */
    public updatePerson(addPersonRequest: AddPersonRequest, options?: RawAxiosRequestConfig) {
        return AdminPersonApiFp(this.configuration).updatePerson(addPersonRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UpdatePersonRequest} updatePersonRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminPersonApi
     */
    public updatePersonDetails(updatePersonRequest: UpdatePersonRequest, options?: RawAxiosRequestConfig) {
        return AdminPersonApiFp(this.configuration).updatePersonDetails(updatePersonRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

