/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EditLinkRequest } from '../model';
// @ts-ignore
import type { EditLinkResult } from '../model';
/**
 * AdminLinksApi - axios parameter creator
 * @export
 */
export const AdminLinksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {EditLinkRequest} editLinkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLink: async (editLinkRequest: EditLinkRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'editLinkRequest' is not null or undefined
            assertParamExists('deleteLink', 'editLinkRequest', editLinkRequest)
            const localVarPath = `/admin/deleteLink/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(editLinkRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {EditLinkRequest} editLinkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editLink: async (editLinkRequest: EditLinkRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'editLinkRequest' is not null or undefined
            assertParamExists('editLink', 'editLinkRequest', editLinkRequest)
            const localVarPath = `/admin/editLink/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(editLinkRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminLinksApi - functional programming interface
 * @export
 */
export const AdminLinksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminLinksApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {EditLinkRequest} editLinkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteLink(editLinkRequest: EditLinkRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EditLinkResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteLink(editLinkRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminLinksApi.deleteLink']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {EditLinkRequest} editLinkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editLink(editLinkRequest: EditLinkRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EditLinkResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.editLink(editLinkRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminLinksApi.editLink']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminLinksApi - factory interface
 * @export
 */
export const AdminLinksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminLinksApiFp(configuration)
    return {
        /**
         * 
         * @param {EditLinkRequest} editLinkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLink(editLinkRequest: EditLinkRequest, options?: RawAxiosRequestConfig): AxiosPromise<EditLinkResult> {
            return localVarFp.deleteLink(editLinkRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {EditLinkRequest} editLinkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editLink(editLinkRequest: EditLinkRequest, options?: RawAxiosRequestConfig): AxiosPromise<EditLinkResult> {
            return localVarFp.editLink(editLinkRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminLinksApi - object-oriented interface
 * @export
 * @class AdminLinksApi
 * @extends {BaseAPI}
 */
export class AdminLinksApi extends BaseAPI {
    /**
     * 
     * @param {EditLinkRequest} editLinkRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminLinksApi
     */
    public deleteLink(editLinkRequest: EditLinkRequest, options?: RawAxiosRequestConfig) {
        return AdminLinksApiFp(this.configuration).deleteLink(editLinkRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {EditLinkRequest} editLinkRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminLinksApi
     */
    public editLink(editLinkRequest: EditLinkRequest, options?: RawAxiosRequestConfig) {
        return AdminLinksApiFp(this.configuration).editLink(editLinkRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

