/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddLetterRequest } from '../model';
// @ts-ignore
import type { AddLetterResult } from '../model';
// @ts-ignore
import type { DeleteLetterRequest } from '../model';
// @ts-ignore
import type { DeleteLetterResult } from '../model';
// @ts-ignore
import type { LetterRequest } from '../model';
// @ts-ignore
import type { LetterResult } from '../model';
/**
 * AdminLetterApi - axios parameter creator
 * @export
 */
export const AdminLetterApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AddLetterRequest} addLetterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLetter: async (addLetterRequest: AddLetterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addLetterRequest' is not null or undefined
            assertParamExists('addLetter', 'addLetterRequest', addLetterRequest)
            const localVarPath = `/admin/addLetter/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addLetterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DeleteLetterRequest} deleteLetterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLetter: async (deleteLetterRequest: DeleteLetterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteLetterRequest' is not null or undefined
            assertParamExists('deleteLetter', 'deleteLetterRequest', deleteLetterRequest)
            const localVarPath = `/admin/deleteLetter/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteLetterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLetter: async (letterRequest: LetterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'letterRequest' is not null or undefined
            assertParamExists('updateLetter', 'letterRequest', letterRequest)
            const localVarPath = `/admin/updateLetter/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(letterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLetterComment: async (letterRequest: LetterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'letterRequest' is not null or undefined
            assertParamExists('updateLetterComment', 'letterRequest', letterRequest)
            const localVarPath = `/admin/updateLetterComment/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(letterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminLetterApi - functional programming interface
 * @export
 */
export const AdminLetterApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminLetterApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {AddLetterRequest} addLetterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addLetter(addLetterRequest: AddLetterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AddLetterResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addLetter(addLetterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminLetterApi.addLetter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {DeleteLetterRequest} deleteLetterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteLetter(deleteLetterRequest: DeleteLetterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteLetterResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteLetter(deleteLetterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminLetterApi.deleteLetter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateLetter(letterRequest: LetterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LetterResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateLetter(letterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminLetterApi.updateLetter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateLetterComment(letterRequest: LetterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LetterResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateLetterComment(letterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminLetterApi.updateLetterComment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminLetterApi - factory interface
 * @export
 */
export const AdminLetterApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminLetterApiFp(configuration)
    return {
        /**
         * 
         * @param {AddLetterRequest} addLetterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLetter(addLetterRequest: AddLetterRequest, options?: RawAxiosRequestConfig): AxiosPromise<AddLetterResult> {
            return localVarFp.addLetter(addLetterRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DeleteLetterRequest} deleteLetterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLetter(deleteLetterRequest: DeleteLetterRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeleteLetterResult> {
            return localVarFp.deleteLetter(deleteLetterRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLetter(letterRequest: LetterRequest, options?: RawAxiosRequestConfig): AxiosPromise<LetterResult> {
            return localVarFp.updateLetter(letterRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLetterComment(letterRequest: LetterRequest, options?: RawAxiosRequestConfig): AxiosPromise<LetterResult> {
            return localVarFp.updateLetterComment(letterRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminLetterApi - object-oriented interface
 * @export
 * @class AdminLetterApi
 * @extends {BaseAPI}
 */
export class AdminLetterApi extends BaseAPI {
    /**
     * 
     * @param {AddLetterRequest} addLetterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminLetterApi
     */
    public addLetter(addLetterRequest: AddLetterRequest, options?: RawAxiosRequestConfig) {
        return AdminLetterApiFp(this.configuration).addLetter(addLetterRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DeleteLetterRequest} deleteLetterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminLetterApi
     */
    public deleteLetter(deleteLetterRequest: DeleteLetterRequest, options?: RawAxiosRequestConfig) {
        return AdminLetterApiFp(this.configuration).deleteLetter(deleteLetterRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {LetterRequest} letterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminLetterApi
     */
    public updateLetter(letterRequest: LetterRequest, options?: RawAxiosRequestConfig) {
        return AdminLetterApiFp(this.configuration).updateLetter(letterRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {LetterRequest} letterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminLetterApi
     */
    public updateLetterComment(letterRequest: LetterRequest, options?: RawAxiosRequestConfig) {
        return AdminLetterApiFp(this.configuration).updateLetterComment(letterRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

