/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { TextRequest } from '../model';
// @ts-ignore
import type { TextResult } from '../model';
/**
 * AdminTextApi - axios parameter creator
 * @export
 */
export const AdminTextApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {TextRequest} textRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateText: async (textRequest: TextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textRequest' is not null or undefined
            assertParamExists('updateText', 'textRequest', textRequest)
            const localVarPath = `/admin/updateText/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(textRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminTextApi - functional programming interface
 * @export
 */
export const AdminTextApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminTextApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {TextRequest} textRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateText(textRequest: TextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateText(textRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminTextApi.updateText']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminTextApi - factory interface
 * @export
 */
export const AdminTextApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminTextApiFp(configuration)
    return {
        /**
         * 
         * @param {TextRequest} textRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateText(textRequest: TextRequest, options?: RawAxiosRequestConfig): AxiosPromise<TextResult> {
            return localVarFp.updateText(textRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminTextApi - object-oriented interface
 * @export
 * @class AdminTextApi
 * @extends {BaseAPI}
 */
export class AdminTextApi extends BaseAPI {
    /**
     * 
     * @param {TextRequest} textRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminTextApi
     */
    public updateText(textRequest: TextRequest, options?: RawAxiosRequestConfig) {
        return AdminTextApiFp(this.configuration).updateText(textRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

