/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PageRequest } from '../model';
// @ts-ignore
import type { PageResult } from '../model';
/**
 * GetPageReferencesControllerApi - axios parameter creator
 * @export
 */
export const GetPageReferencesControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {PageRequest} pageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPage: async (pageRequest: PageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageRequest' is not null or undefined
            assertParamExists('getPage', 'pageRequest', pageRequest)
            const localVarPath = `/get_page_references/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GetPageReferencesControllerApi - functional programming interface
 * @export
 */
export const GetPageReferencesControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GetPageReferencesControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {PageRequest} pageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPage(pageRequest: PageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPage(pageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetPageReferencesControllerApi.getPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GetPageReferencesControllerApi - factory interface
 * @export
 */
export const GetPageReferencesControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GetPageReferencesControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {PageRequest} pageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPage(pageRequest: PageRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageResult> {
            return localVarFp.getPage(pageRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GetPageReferencesControllerApi - object-oriented interface
 * @export
 * @class GetPageReferencesControllerApi
 * @extends {BaseAPI}
 */
export class GetPageReferencesControllerApi extends BaseAPI {
    /**
     * 
     * @param {PageRequest} pageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GetPageReferencesControllerApi
     */
    public getPage(pageRequest: PageRequest, options?: RawAxiosRequestConfig) {
        return GetPageReferencesControllerApiFp(this.configuration).getPage(pageRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

