/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ContentRequest } from '../model';
// @ts-ignore
import type { ContentResult } from '../model';
/**
 * GetContentControllerApi - axios parameter creator
 * @export
 */
export const GetContentControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ContentRequest} contentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPage: async (contentRequest: ContentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contentRequest' is not null or undefined
            assertParamExists('addPage', 'contentRequest', contentRequest)
            const localVarPath = `/get_content/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GetContentControllerApi - functional programming interface
 * @export
 */
export const GetContentControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GetContentControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ContentRequest} contentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addPage(contentRequest: ContentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addPage(contentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetContentControllerApi.addPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GetContentControllerApi - factory interface
 * @export
 */
export const GetContentControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GetContentControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {ContentRequest} contentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPage(contentRequest: ContentRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentResult> {
            return localVarFp.addPage(contentRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GetContentControllerApi - object-oriented interface
 * @export
 * @class GetContentControllerApi
 * @extends {BaseAPI}
 */
export class GetContentControllerApi extends BaseAPI {
    /**
     * 
     * @param {ContentRequest} contentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GetContentControllerApi
     */
    public addPage(contentRequest: ContentRequest, options?: RawAxiosRequestConfig) {
        return GetContentControllerApiFp(this.configuration).addPage(contentRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

