/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HomeTextRequest } from '../model';
// @ts-ignore
import type { HomeTextResult } from '../model';
// @ts-ignore
import type { PageTextRequest } from '../model';
// @ts-ignore
import type { PageTextResult } from '../model';
/**
 * HomeTextApi - axios parameter creator
 * @export
 */
export const HomeTextApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {HomeTextRequest} homeTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHomeText: async (homeTextRequest: HomeTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'homeTextRequest' is not null or undefined
            assertParamExists('getHomeText', 'homeTextRequest', homeTextRequest)
            const localVarPath = `/getHomeText/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(homeTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        switchLanguage: async (pageTextRequest: PageTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageTextRequest' is not null or undefined
            assertParamExists('switchLanguage', 'pageTextRequest', pageTextRequest)
            const localVarPath = `/switchLanguage/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HomeTextApi - functional programming interface
 * @export
 */
export const HomeTextApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HomeTextApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {HomeTextRequest} homeTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHomeText(homeTextRequest: HomeTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HomeTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHomeText(homeTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeTextApi.getHomeText']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async switchLanguage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.switchLanguage(pageTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeTextApi.switchLanguage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HomeTextApi - factory interface
 * @export
 */
export const HomeTextApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HomeTextApiFp(configuration)
    return {
        /**
         * 
         * @param {HomeTextRequest} homeTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHomeText(homeTextRequest: HomeTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<HomeTextResult> {
            return localVarFp.getHomeText(homeTextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        switchLanguage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageTextResult> {
            return localVarFp.switchLanguage(pageTextRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HomeTextApi - object-oriented interface
 * @export
 * @class HomeTextApi
 * @extends {BaseAPI}
 */
export class HomeTextApi extends BaseAPI {
    /**
     * 
     * @param {HomeTextRequest} homeTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeTextApi
     */
    public getHomeText(homeTextRequest: HomeTextRequest, options?: RawAxiosRequestConfig) {
        return HomeTextApiFp(this.configuration).getHomeText(homeTextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PageTextRequest} pageTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeTextApi
     */
    public switchLanguage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig) {
        return HomeTextApiFp(this.configuration).switchLanguage(pageTextRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

