/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HomeTextRequest } from '../model';
// @ts-ignore
import type { HomeTextResult } from '../model';
// @ts-ignore
import type { PageTextRequest } from '../model';
// @ts-ignore
import type { PageTextResult } from '../model';
/**
 * HomeTextGetControllerApi - axios parameter creator
 * @export
 */
export const HomeTextGetControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextChapter: async (pageTextRequest: PageTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageTextRequest' is not null or undefined
            assertParamExists('getNextChapter', 'pageTextRequest', pageTextRequest)
            const localVarPath = `/get_next_chapter`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextPage: async (pageTextRequest: PageTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageTextRequest' is not null or undefined
            assertParamExists('getNextPage', 'pageTextRequest', pageTextRequest)
            const localVarPath = `/get_next_page/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPage1: async (pageTextRequest: PageTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageTextRequest' is not null or undefined
            assertParamExists('getPage1', 'pageTextRequest', pageTextRequest)
            const localVarPath = `/get_page_page/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPreviousChapter: async (pageTextRequest: PageTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageTextRequest' is not null or undefined
            assertParamExists('getPreviousChapter', 'pageTextRequest', pageTextRequest)
            const localVarPath = `/get_previous_chapter`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPreviousPage: async (pageTextRequest: PageTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageTextRequest' is not null or undefined
            assertParamExists('getPreviousPage', 'pageTextRequest', pageTextRequest)
            const localVarPath = `/get_previous_page/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {HomeTextRequest} homeTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getText1: async (homeTextRequest: HomeTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'homeTextRequest' is not null or undefined
            assertParamExists('getText1', 'homeTextRequest', homeTextRequest)
            const localVarPath = `/get_page_text/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(homeTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        switchLanguage: async (pageTextRequest: PageTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageTextRequest' is not null or undefined
            assertParamExists('switchLanguage', 'pageTextRequest', pageTextRequest)
            const localVarPath = `/switch_page_text/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HomeTextGetControllerApi - functional programming interface
 * @export
 */
export const HomeTextGetControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HomeTextGetControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNextChapter(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNextChapter(pageTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeTextGetControllerApi.getNextChapter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNextPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNextPage(pageTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeTextGetControllerApi.getNextPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPage1(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPage1(pageTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeTextGetControllerApi.getPage1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPreviousChapter(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPreviousChapter(pageTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeTextGetControllerApi.getPreviousChapter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPreviousPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPreviousPage(pageTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeTextGetControllerApi.getPreviousPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {HomeTextRequest} homeTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getText1(homeTextRequest: HomeTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HomeTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getText1(homeTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeTextGetControllerApi.getText1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async switchLanguage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.switchLanguage(pageTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeTextGetControllerApi.switchLanguage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HomeTextGetControllerApi - factory interface
 * @export
 */
export const HomeTextGetControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HomeTextGetControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextChapter(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageTextResult> {
            return localVarFp.getNextChapter(pageTextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageTextResult> {
            return localVarFp.getNextPage(pageTextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPage1(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageTextResult> {
            return localVarFp.getPage1(pageTextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPreviousChapter(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageTextResult> {
            return localVarFp.getPreviousChapter(pageTextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPreviousPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageTextResult> {
            return localVarFp.getPreviousPage(pageTextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {HomeTextRequest} homeTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getText1(homeTextRequest: HomeTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<HomeTextResult> {
            return localVarFp.getText1(homeTextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        switchLanguage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageTextResult> {
            return localVarFp.switchLanguage(pageTextRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HomeTextGetControllerApi - object-oriented interface
 * @export
 * @class HomeTextGetControllerApi
 * @extends {BaseAPI}
 */
export class HomeTextGetControllerApi extends BaseAPI {
    /**
     * 
     * @param {PageTextRequest} pageTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeTextGetControllerApi
     */
    public getNextChapter(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig) {
        return HomeTextGetControllerApiFp(this.configuration).getNextChapter(pageTextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PageTextRequest} pageTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeTextGetControllerApi
     */
    public getNextPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig) {
        return HomeTextGetControllerApiFp(this.configuration).getNextPage(pageTextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PageTextRequest} pageTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeTextGetControllerApi
     */
    public getPage1(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig) {
        return HomeTextGetControllerApiFp(this.configuration).getPage1(pageTextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PageTextRequest} pageTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeTextGetControllerApi
     */
    public getPreviousChapter(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig) {
        return HomeTextGetControllerApiFp(this.configuration).getPreviousChapter(pageTextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PageTextRequest} pageTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeTextGetControllerApi
     */
    public getPreviousPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig) {
        return HomeTextGetControllerApiFp(this.configuration).getPreviousPage(pageTextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {HomeTextRequest} homeTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeTextGetControllerApi
     */
    public getText1(homeTextRequest: HomeTextRequest, options?: RawAxiosRequestConfig) {
        return HomeTextGetControllerApiFp(this.configuration).getText1(homeTextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PageTextRequest} pageTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeTextGetControllerApi
     */
    public switchLanguage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig) {
        return HomeTextGetControllerApiFp(this.configuration).switchLanguage(pageTextRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

