/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ImagesRequest } from '../model';
// @ts-ignore
import type { ImagesResult } from '../model';
/**
 * ImagesControllerApi - axios parameter creator
 * @export
 */
export const ImagesControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ImagesRequest} imagesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLetterImages: async (imagesRequest: ImagesRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'imagesRequest' is not null or undefined
            assertParamExists('getLetterImages', 'imagesRequest', imagesRequest)
            const localVarPath = `/get_letter_images/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(imagesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ImagesControllerApi - functional programming interface
 * @export
 */
export const ImagesControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ImagesControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ImagesRequest} imagesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLetterImages(imagesRequest: ImagesRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImagesResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLetterImages(imagesRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ImagesControllerApi.getLetterImages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ImagesControllerApi - factory interface
 * @export
 */
export const ImagesControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ImagesControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {ImagesRequest} imagesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLetterImages(imagesRequest: ImagesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImagesResult> {
            return localVarFp.getLetterImages(imagesRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ImagesControllerApi - object-oriented interface
 * @export
 * @class ImagesControllerApi
 * @extends {BaseAPI}
 */
export class ImagesControllerApi extends BaseAPI {
    /**
     * 
     * @param {ImagesRequest} imagesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImagesControllerApi
     */
    public getLetterImages(imagesRequest: ImagesRequest, options?: RawAxiosRequestConfig) {
        return ImagesControllerApiFp(this.configuration).getLetterImages(imagesRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

