/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { LettersResult } from '../model';
// @ts-ignore
import type { PersonLettersRequest } from '../model';
/**
 * LettersFromPersonControllerApi - axios parameter creator
 * @export
 */
export const LettersFromPersonControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {PersonLettersRequest} personLettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLetters1: async (personLettersRequest: PersonLettersRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personLettersRequest' is not null or undefined
            assertParamExists('getLetters1', 'personLettersRequest', personLettersRequest)
            const localVarPath = `/get_letters_from_person/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(personLettersRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LettersFromPersonControllerApi - functional programming interface
 * @export
 */
export const LettersFromPersonControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LettersFromPersonControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {PersonLettersRequest} personLettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLetters1(personLettersRequest: PersonLettersRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LettersResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLetters1(personLettersRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LettersFromPersonControllerApi.getLetters1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LettersFromPersonControllerApi - factory interface
 * @export
 */
export const LettersFromPersonControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LettersFromPersonControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {PersonLettersRequest} personLettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLetters1(personLettersRequest: PersonLettersRequest, options?: RawAxiosRequestConfig): AxiosPromise<LettersResult> {
            return localVarFp.getLetters1(personLettersRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LettersFromPersonControllerApi - object-oriented interface
 * @export
 * @class LettersFromPersonControllerApi
 * @extends {BaseAPI}
 */
export class LettersFromPersonControllerApi extends BaseAPI {
    /**
     * 
     * @param {PersonLettersRequest} personLettersRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LettersFromPersonControllerApi
     */
    public getLetters1(personLettersRequest: PersonLettersRequest, options?: RawAxiosRequestConfig) {
        return LettersFromPersonControllerApiFp(this.configuration).getLetters1(personLettersRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

