/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DeleteLetterRequest } from '../model';
// @ts-ignore
import type { DeleteLetterResult } from '../model';
/**
 * LetterDeleteControllerApi - axios parameter creator
 * @export
 */
export const LetterDeleteControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {DeleteLetterRequest} deleteLetterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLetter: async (deleteLetterRequest: DeleteLetterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteLetterRequest' is not null or undefined
            assertParamExists('addLetter', 'deleteLetterRequest', deleteLetterRequest)
            const localVarPath = `/admin/delete_letter/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteLetterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LetterDeleteControllerApi - functional programming interface
 * @export
 */
export const LetterDeleteControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LetterDeleteControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {DeleteLetterRequest} deleteLetterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addLetter(deleteLetterRequest: DeleteLetterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteLetterResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addLetter(deleteLetterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LetterDeleteControllerApi.addLetter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LetterDeleteControllerApi - factory interface
 * @export
 */
export const LetterDeleteControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LetterDeleteControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {DeleteLetterRequest} deleteLetterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLetter(deleteLetterRequest: DeleteLetterRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeleteLetterResult> {
            return localVarFp.addLetter(deleteLetterRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LetterDeleteControllerApi - object-oriented interface
 * @export
 * @class LetterDeleteControllerApi
 * @extends {BaseAPI}
 */
export class LetterDeleteControllerApi extends BaseAPI {
    /**
     * 
     * @param {DeleteLetterRequest} deleteLetterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LetterDeleteControllerApi
     */
    public addLetter(deleteLetterRequest: DeleteLetterRequest, options?: RawAxiosRequestConfig) {
        return LetterDeleteControllerApiFp(this.configuration).addLetter(deleteLetterRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

