/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { LetterRequest } from '../model';
// @ts-ignore
import type { LetterResult } from '../model';
// @ts-ignore
import type { LettersRequest } from '../model';
// @ts-ignore
import type { LettersResult } from '../model';
// @ts-ignore
import type { LocationLettersRequest } from '../model';
// @ts-ignore
import type { PersonLettersRequest } from '../model';
/**
 * LettersApi - axios parameter creator
 * @export
 */
export const LettersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLetter: async (letterRequest: LetterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'letterRequest' is not null or undefined
            assertParamExists('getLetter', 'letterRequest', letterRequest)
            const localVarPath = `/getLetter/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(letterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LettersRequest} lettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLetters: async (lettersRequest: LettersRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'lettersRequest' is not null or undefined
            assertParamExists('getLetters', 'lettersRequest', lettersRequest)
            const localVarPath = `/getLetters/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(lettersRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LocationLettersRequest} locationLettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLettersForLocation: async (locationLettersRequest: LocationLettersRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'locationLettersRequest' is not null or undefined
            assertParamExists('getLettersForLocation', 'locationLettersRequest', locationLettersRequest)
            const localVarPath = `/getLettersForLocation/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(locationLettersRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PersonLettersRequest} personLettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLettersForPerson: async (personLettersRequest: PersonLettersRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personLettersRequest' is not null or undefined
            assertParamExists('getLettersForPerson', 'personLettersRequest', personLettersRequest)
            const localVarPath = `/getLettersForPerson/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(personLettersRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextLetter: async (letterRequest: LetterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'letterRequest' is not null or undefined
            assertParamExists('getNextLetter', 'letterRequest', letterRequest)
            const localVarPath = `/getNextLetter/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(letterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPreviousLetter: async (letterRequest: LetterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'letterRequest' is not null or undefined
            assertParamExists('getPreviousLetter', 'letterRequest', letterRequest)
            const localVarPath = `/getPreviousLetter/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(letterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LettersApi - functional programming interface
 * @export
 */
export const LettersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LettersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLetter(letterRequest: LetterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LetterResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLetter(letterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LettersApi.getLetter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {LettersRequest} lettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLetters(lettersRequest: LettersRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LettersResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLetters(lettersRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LettersApi.getLetters']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {LocationLettersRequest} locationLettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLettersForLocation(locationLettersRequest: LocationLettersRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LettersResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLettersForLocation(locationLettersRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LettersApi.getLettersForLocation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PersonLettersRequest} personLettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLettersForPerson(personLettersRequest: PersonLettersRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LettersResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLettersForPerson(personLettersRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LettersApi.getLettersForPerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNextLetter(letterRequest: LetterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LetterResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNextLetter(letterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LettersApi.getNextLetter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPreviousLetter(letterRequest: LetterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LetterResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPreviousLetter(letterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LettersApi.getPreviousLetter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LettersApi - factory interface
 * @export
 */
export const LettersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LettersApiFp(configuration)
    return {
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLetter(letterRequest: LetterRequest, options?: RawAxiosRequestConfig): AxiosPromise<LetterResult> {
            return localVarFp.getLetter(letterRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {LettersRequest} lettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLetters(lettersRequest: LettersRequest, options?: RawAxiosRequestConfig): AxiosPromise<LettersResult> {
            return localVarFp.getLetters(lettersRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {LocationLettersRequest} locationLettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLettersForLocation(locationLettersRequest: LocationLettersRequest, options?: RawAxiosRequestConfig): AxiosPromise<LettersResult> {
            return localVarFp.getLettersForLocation(locationLettersRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PersonLettersRequest} personLettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLettersForPerson(personLettersRequest: PersonLettersRequest, options?: RawAxiosRequestConfig): AxiosPromise<LettersResult> {
            return localVarFp.getLettersForPerson(personLettersRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextLetter(letterRequest: LetterRequest, options?: RawAxiosRequestConfig): AxiosPromise<LetterResult> {
            return localVarFp.getNextLetter(letterRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPreviousLetter(letterRequest: LetterRequest, options?: RawAxiosRequestConfig): AxiosPromise<LetterResult> {
            return localVarFp.getPreviousLetter(letterRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LettersApi - object-oriented interface
 * @export
 * @class LettersApi
 * @extends {BaseAPI}
 */
export class LettersApi extends BaseAPI {
    /**
     * 
     * @param {LetterRequest} letterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LettersApi
     */
    public getLetter(letterRequest: LetterRequest, options?: RawAxiosRequestConfig) {
        return LettersApiFp(this.configuration).getLetter(letterRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {LettersRequest} lettersRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LettersApi
     */
    public getLetters(lettersRequest: LettersRequest, options?: RawAxiosRequestConfig) {
        return LettersApiFp(this.configuration).getLetters(lettersRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {LocationLettersRequest} locationLettersRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LettersApi
     */
    public getLettersForLocation(locationLettersRequest: LocationLettersRequest, options?: RawAxiosRequestConfig) {
        return LettersApiFp(this.configuration).getLettersForLocation(locationLettersRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PersonLettersRequest} personLettersRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LettersApi
     */
    public getLettersForPerson(personLettersRequest: PersonLettersRequest, options?: RawAxiosRequestConfig) {
        return LettersApiFp(this.configuration).getLettersForPerson(personLettersRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {LetterRequest} letterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LettersApi
     */
    public getNextLetter(letterRequest: LetterRequest, options?: RawAxiosRequestConfig) {
        return LettersApiFp(this.configuration).getNextLetter(letterRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {LetterRequest} letterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LettersApi
     */
    public getPreviousLetter(letterRequest: LetterRequest, options?: RawAxiosRequestConfig) {
        return LettersApiFp(this.configuration).getPreviousLetter(letterRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

