/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { LetterRequest } from '../model';
// @ts-ignore
import type { LetterResult } from '../model';
/**
 * LetterUpdateCommentControllerApi - axios parameter creator
 * @export
 */
export const LetterUpdateCommentControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLetterComment: async (letterRequest: LetterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'letterRequest' is not null or undefined
            assertParamExists('updateLetterComment', 'letterRequest', letterRequest)
            const localVarPath = `/admin/update_letter_comment/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(letterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LetterUpdateCommentControllerApi - functional programming interface
 * @export
 */
export const LetterUpdateCommentControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LetterUpdateCommentControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateLetterComment(letterRequest: LetterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LetterResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateLetterComment(letterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LetterUpdateCommentControllerApi.updateLetterComment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LetterUpdateCommentControllerApi - factory interface
 * @export
 */
export const LetterUpdateCommentControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LetterUpdateCommentControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {LetterRequest} letterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLetterComment(letterRequest: LetterRequest, options?: RawAxiosRequestConfig): AxiosPromise<LetterResult> {
            return localVarFp.updateLetterComment(letterRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LetterUpdateCommentControllerApi - object-oriented interface
 * @export
 * @class LetterUpdateCommentControllerApi
 * @extends {BaseAPI}
 */
export class LetterUpdateCommentControllerApi extends BaseAPI {
    /**
     * 
     * @param {LetterRequest} letterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LetterUpdateCommentControllerApi
     */
    public updateLetterComment(letterRequest: LetterRequest, options?: RawAxiosRequestConfig) {
        return LetterUpdateCommentControllerApiFp(this.configuration).updateLetterComment(letterRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

