/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { LettersRequest } from '../model';
// @ts-ignore
import type { LettersResult } from '../model';
/**
 * LetterGetAllControllerApi - axios parameter creator
 * @export
 */
export const LetterGetAllControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {LettersRequest} lettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLetters3: async (lettersRequest: LettersRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'lettersRequest' is not null or undefined
            assertParamExists('getLetters3', 'lettersRequest', lettersRequest)
            const localVarPath = `/get_letters/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(lettersRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LettersRequest} lettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLettersByDate: async (lettersRequest: LettersRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'lettersRequest' is not null or undefined
            assertParamExists('getLettersByDate', 'lettersRequest', lettersRequest)
            const localVarPath = `/get_letters_by_date/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(lettersRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LetterGetAllControllerApi - functional programming interface
 * @export
 */
export const LetterGetAllControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LetterGetAllControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {LettersRequest} lettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLetters3(lettersRequest: LettersRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LettersResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLetters3(lettersRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LetterGetAllControllerApi.getLetters3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {LettersRequest} lettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLettersByDate(lettersRequest: LettersRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LettersResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLettersByDate(lettersRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LetterGetAllControllerApi.getLettersByDate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LetterGetAllControllerApi - factory interface
 * @export
 */
export const LetterGetAllControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LetterGetAllControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {LettersRequest} lettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLetters3(lettersRequest: LettersRequest, options?: RawAxiosRequestConfig): AxiosPromise<LettersResult> {
            return localVarFp.getLetters3(lettersRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {LettersRequest} lettersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLettersByDate(lettersRequest: LettersRequest, options?: RawAxiosRequestConfig): AxiosPromise<LettersResult> {
            return localVarFp.getLettersByDate(lettersRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LetterGetAllControllerApi - object-oriented interface
 * @export
 * @class LetterGetAllControllerApi
 * @extends {BaseAPI}
 */
export class LetterGetAllControllerApi extends BaseAPI {
    /**
     * 
     * @param {LettersRequest} lettersRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LetterGetAllControllerApi
     */
    public getLetters3(lettersRequest: LettersRequest, options?: RawAxiosRequestConfig) {
        return LetterGetAllControllerApiFp(this.configuration).getLetters3(lettersRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {LettersRequest} lettersRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LetterGetAllControllerApi
     */
    public getLettersByDate(lettersRequest: LettersRequest, options?: RawAxiosRequestConfig) {
        return LetterGetAllControllerApiFp(this.configuration).getLettersByDate(lettersRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

