/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddLetterRequest } from '../model';
// @ts-ignore
import type { AddLetterResult } from '../model';
/**
 * LetterAddControllerApi - axios parameter creator
 * @export
 */
export const LetterAddControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AddLetterRequest} addLetterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLetter1: async (addLetterRequest: AddLetterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addLetterRequest' is not null or undefined
            assertParamExists('addLetter1', 'addLetterRequest', addLetterRequest)
            const localVarPath = `/admin/add_letter/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addLetterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LetterAddControllerApi - functional programming interface
 * @export
 */
export const LetterAddControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LetterAddControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {AddLetterRequest} addLetterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addLetter1(addLetterRequest: AddLetterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AddLetterResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addLetter1(addLetterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LetterAddControllerApi.addLetter1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LetterAddControllerApi - factory interface
 * @export
 */
export const LetterAddControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LetterAddControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {AddLetterRequest} addLetterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLetter1(addLetterRequest: AddLetterRequest, options?: RawAxiosRequestConfig): AxiosPromise<AddLetterResult> {
            return localVarFp.addLetter1(addLetterRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LetterAddControllerApi - object-oriented interface
 * @export
 * @class LetterAddControllerApi
 * @extends {BaseAPI}
 */
export class LetterAddControllerApi extends BaseAPI {
    /**
     * 
     * @param {AddLetterRequest} addLetterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LetterAddControllerApi
     */
    public addLetter1(addLetterRequest: AddLetterRequest, options?: RawAxiosRequestConfig) {
        return LetterAddControllerApiFp(this.configuration).addLetter1(addLetterRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

