/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddLocationRequest } from '../model';
// @ts-ignore
import type { AddLocationResult } from '../model';
/**
 * LocationAddControllerApi - axios parameter creator
 * @export
 */
export const LocationAddControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AddLocationRequest} addLocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLocation: async (addLocationRequest: AddLocationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addLocationRequest' is not null or undefined
            assertParamExists('addLocation', 'addLocationRequest', addLocationRequest)
            const localVarPath = `/admin/add_location/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addLocationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LocationAddControllerApi - functional programming interface
 * @export
 */
export const LocationAddControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LocationAddControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {AddLocationRequest} addLocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addLocation(addLocationRequest: AddLocationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AddLocationResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addLocation(addLocationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationAddControllerApi.addLocation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LocationAddControllerApi - factory interface
 * @export
 */
export const LocationAddControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LocationAddControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {AddLocationRequest} addLocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLocation(addLocationRequest: AddLocationRequest, options?: RawAxiosRequestConfig): AxiosPromise<AddLocationResult> {
            return localVarFp.addLocation(addLocationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LocationAddControllerApi - object-oriented interface
 * @export
 * @class LocationAddControllerApi
 * @extends {BaseAPI}
 */
export class LocationAddControllerApi extends BaseAPI {
    /**
     * 
     * @param {AddLocationRequest} addLocationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationAddControllerApi
     */
    public addLocation(addLocationRequest: AddLocationRequest, options?: RawAxiosRequestConfig) {
        return LocationAddControllerApiFp(this.configuration).addLocation(addLocationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

