/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CombineLocationRequest } from '../model';
// @ts-ignore
import type { CombineLocationResult } from '../model';
/**
 * LocationCombineControllerApi - axios parameter creator
 * @export
 */
export const LocationCombineControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CombineLocationRequest} combineLocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCombinePerson1: async (combineLocationRequest: CombineLocationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'combineLocationRequest' is not null or undefined
            assertParamExists('getCombinePerson1', 'combineLocationRequest', combineLocationRequest)
            const localVarPath = `/admin/get_combine_location/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(combineLocationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CombineLocationRequest} combineLocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putCombinePerson1: async (combineLocationRequest: CombineLocationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'combineLocationRequest' is not null or undefined
            assertParamExists('putCombinePerson1', 'combineLocationRequest', combineLocationRequest)
            const localVarPath = `/admin/put_combine_location/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(combineLocationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LocationCombineControllerApi - functional programming interface
 * @export
 */
export const LocationCombineControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LocationCombineControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CombineLocationRequest} combineLocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCombinePerson1(combineLocationRequest: CombineLocationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CombineLocationResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCombinePerson1(combineLocationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationCombineControllerApi.getCombinePerson1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CombineLocationRequest} combineLocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putCombinePerson1(combineLocationRequest: CombineLocationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CombineLocationResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putCombinePerson1(combineLocationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationCombineControllerApi.putCombinePerson1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LocationCombineControllerApi - factory interface
 * @export
 */
export const LocationCombineControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LocationCombineControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {CombineLocationRequest} combineLocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCombinePerson1(combineLocationRequest: CombineLocationRequest, options?: RawAxiosRequestConfig): AxiosPromise<CombineLocationResult> {
            return localVarFp.getCombinePerson1(combineLocationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CombineLocationRequest} combineLocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putCombinePerson1(combineLocationRequest: CombineLocationRequest, options?: RawAxiosRequestConfig): AxiosPromise<CombineLocationResult> {
            return localVarFp.putCombinePerson1(combineLocationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LocationCombineControllerApi - object-oriented interface
 * @export
 * @class LocationCombineControllerApi
 * @extends {BaseAPI}
 */
export class LocationCombineControllerApi extends BaseAPI {
    /**
     * 
     * @param {CombineLocationRequest} combineLocationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationCombineControllerApi
     */
    public getCombinePerson1(combineLocationRequest: CombineLocationRequest, options?: RawAxiosRequestConfig) {
        return LocationCombineControllerApiFp(this.configuration).getCombinePerson1(combineLocationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CombineLocationRequest} combineLocationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationCombineControllerApi
     */
    public putCombinePerson1(combineLocationRequest: CombineLocationRequest, options?: RawAxiosRequestConfig) {
        return LocationCombineControllerApiFp(this.configuration).putCombinePerson1(combineLocationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

