/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DeleteLocationRequest } from '../model';
// @ts-ignore
import type { DeleteLocationResult } from '../model';
/**
 * LocationDeleteControllerApi - axios parameter creator
 * @export
 */
export const LocationDeleteControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {DeleteLocationRequest} deleteLocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPerson3: async (deleteLocationRequest: DeleteLocationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteLocationRequest' is not null or undefined
            assertParamExists('getPerson3', 'deleteLocationRequest', deleteLocationRequest)
            const localVarPath = `/admin/delete_location/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteLocationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LocationDeleteControllerApi - functional programming interface
 * @export
 */
export const LocationDeleteControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LocationDeleteControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {DeleteLocationRequest} deleteLocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPerson3(deleteLocationRequest: DeleteLocationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteLocationResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPerson3(deleteLocationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocationDeleteControllerApi.getPerson3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LocationDeleteControllerApi - factory interface
 * @export
 */
export const LocationDeleteControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LocationDeleteControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {DeleteLocationRequest} deleteLocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPerson3(deleteLocationRequest: DeleteLocationRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeleteLocationResult> {
            return localVarFp.getPerson3(deleteLocationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LocationDeleteControllerApi - object-oriented interface
 * @export
 * @class LocationDeleteControllerApi
 * @extends {BaseAPI}
 */
export class LocationDeleteControllerApi extends BaseAPI {
    /**
     * 
     * @param {DeleteLocationRequest} deleteLocationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationDeleteControllerApi
     */
    public getPerson3(deleteLocationRequest: DeleteLocationRequest, options?: RawAxiosRequestConfig) {
        return LocationDeleteControllerApiFp(this.configuration).getPerson3(deleteLocationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

