/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PageTextRequest } from '../model';
// @ts-ignore
import type { PageTextResult } from '../model';
/**
 * PageApi - axios parameter creator
 * @export
 */
export const PageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextChapter: async (pageTextRequest: PageTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageTextRequest' is not null or undefined
            assertParamExists('getNextChapter', 'pageTextRequest', pageTextRequest)
            const localVarPath = `/getNextChapter`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextPage: async (pageTextRequest: PageTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageTextRequest' is not null or undefined
            assertParamExists('getNextPage', 'pageTextRequest', pageTextRequest)
            const localVarPath = `/getNextPage/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPage: async (pageTextRequest: PageTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageTextRequest' is not null or undefined
            assertParamExists('getPage', 'pageTextRequest', pageTextRequest)
            const localVarPath = `/getPage/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPreviousChapter: async (pageTextRequest: PageTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageTextRequest' is not null or undefined
            assertParamExists('getPreviousChapter', 'pageTextRequest', pageTextRequest)
            const localVarPath = `/getPreviousChapter`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPreviousPage: async (pageTextRequest: PageTextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageTextRequest' is not null or undefined
            assertParamExists('getPreviousPage', 'pageTextRequest', pageTextRequest)
            const localVarPath = `/getPreviousPage/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageTextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PageApi - functional programming interface
 * @export
 */
export const PageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PageApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNextChapter(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNextChapter(pageTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PageApi.getNextChapter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNextPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNextPage(pageTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PageApi.getNextPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPage(pageTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PageApi.getPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPreviousChapter(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPreviousChapter(pageTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PageApi.getPreviousChapter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPreviousPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageTextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPreviousPage(pageTextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PageApi.getPreviousPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PageApi - factory interface
 * @export
 */
export const PageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PageApiFp(configuration)
    return {
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextChapter(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageTextResult> {
            return localVarFp.getNextChapter(pageTextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNextPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageTextResult> {
            return localVarFp.getNextPage(pageTextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageTextResult> {
            return localVarFp.getPage(pageTextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPreviousChapter(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageTextResult> {
            return localVarFp.getPreviousChapter(pageTextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PageTextRequest} pageTextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPreviousPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig): AxiosPromise<PageTextResult> {
            return localVarFp.getPreviousPage(pageTextRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PageApi - object-oriented interface
 * @export
 * @class PageApi
 * @extends {BaseAPI}
 */
export class PageApi extends BaseAPI {
    /**
     * 
     * @param {PageTextRequest} pageTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PageApi
     */
    public getNextChapter(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig) {
        return PageApiFp(this.configuration).getNextChapter(pageTextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PageTextRequest} pageTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PageApi
     */
    public getNextPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig) {
        return PageApiFp(this.configuration).getNextPage(pageTextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PageTextRequest} pageTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PageApi
     */
    public getPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig) {
        return PageApiFp(this.configuration).getPage(pageTextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PageTextRequest} pageTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PageApi
     */
    public getPreviousChapter(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig) {
        return PageApiFp(this.configuration).getPreviousChapter(pageTextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PageTextRequest} pageTextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PageApi
     */
    public getPreviousPage(pageTextRequest: PageTextRequest, options?: RawAxiosRequestConfig) {
        return PageApiFp(this.configuration).getPreviousPage(pageTextRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

