/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DeletePersonRequest } from '../model';
// @ts-ignore
import type { PersonResult } from '../model';
/**
 * PersonDeleteControllerApi - axios parameter creator
 * @export
 */
export const PersonDeleteControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {DeletePersonRequest} deletePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPerson2: async (deletePersonRequest: DeletePersonRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deletePersonRequest' is not null or undefined
            assertParamExists('getPerson2', 'deletePersonRequest', deletePersonRequest)
            const localVarPath = `/admin/delete_person/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deletePersonRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PersonDeleteControllerApi - functional programming interface
 * @export
 */
export const PersonDeleteControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PersonDeleteControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {DeletePersonRequest} deletePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPerson2(deletePersonRequest: DeletePersonRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPerson2(deletePersonRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonDeleteControllerApi.getPerson2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PersonDeleteControllerApi - factory interface
 * @export
 */
export const PersonDeleteControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PersonDeleteControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {DeletePersonRequest} deletePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPerson2(deletePersonRequest: DeletePersonRequest, options?: RawAxiosRequestConfig): AxiosPromise<PersonResult> {
            return localVarFp.getPerson2(deletePersonRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PersonDeleteControllerApi - object-oriented interface
 * @export
 * @class PersonDeleteControllerApi
 * @extends {BaseAPI}
 */
export class PersonDeleteControllerApi extends BaseAPI {
    /**
     * 
     * @param {DeletePersonRequest} deletePersonRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonDeleteControllerApi
     */
    public getPerson2(deletePersonRequest: DeletePersonRequest, options?: RawAxiosRequestConfig) {
        return PersonDeleteControllerApiFp(this.configuration).getPerson2(deletePersonRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

