/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CombinePersonRequest } from '../model';
// @ts-ignore
import type { CombinePersonResult } from '../model';
/**
 * PersonCombineControllerApi - axios parameter creator
 * @export
 */
export const PersonCombineControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CombinePersonRequest} combinePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCombinePerson: async (combinePersonRequest: CombinePersonRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'combinePersonRequest' is not null or undefined
            assertParamExists('getCombinePerson', 'combinePersonRequest', combinePersonRequest)
            const localVarPath = `/admin/get_combine_person/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(combinePersonRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CombinePersonRequest} combinePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putCombinePerson: async (combinePersonRequest: CombinePersonRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'combinePersonRequest' is not null or undefined
            assertParamExists('putCombinePerson', 'combinePersonRequest', combinePersonRequest)
            const localVarPath = `/admin/put_combine_person/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(combinePersonRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PersonCombineControllerApi - functional programming interface
 * @export
 */
export const PersonCombineControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PersonCombineControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CombinePersonRequest} combinePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCombinePerson(combinePersonRequest: CombinePersonRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CombinePersonResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCombinePerson(combinePersonRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonCombineControllerApi.getCombinePerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CombinePersonRequest} combinePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putCombinePerson(combinePersonRequest: CombinePersonRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CombinePersonResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putCombinePerson(combinePersonRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonCombineControllerApi.putCombinePerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PersonCombineControllerApi - factory interface
 * @export
 */
export const PersonCombineControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PersonCombineControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {CombinePersonRequest} combinePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCombinePerson(combinePersonRequest: CombinePersonRequest, options?: RawAxiosRequestConfig): AxiosPromise<CombinePersonResult> {
            return localVarFp.getCombinePerson(combinePersonRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CombinePersonRequest} combinePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putCombinePerson(combinePersonRequest: CombinePersonRequest, options?: RawAxiosRequestConfig): AxiosPromise<CombinePersonResult> {
            return localVarFp.putCombinePerson(combinePersonRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PersonCombineControllerApi - object-oriented interface
 * @export
 * @class PersonCombineControllerApi
 * @extends {BaseAPI}
 */
export class PersonCombineControllerApi extends BaseAPI {
    /**
     * 
     * @param {CombinePersonRequest} combinePersonRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonCombineControllerApi
     */
    public getCombinePerson(combinePersonRequest: CombinePersonRequest, options?: RawAxiosRequestConfig) {
        return PersonCombineControllerApiFp(this.configuration).getCombinePerson(combinePersonRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CombinePersonRequest} combinePersonRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonCombineControllerApi
     */
    public putCombinePerson(combinePersonRequest: CombinePersonRequest, options?: RawAxiosRequestConfig) {
        return PersonCombineControllerApiFp(this.configuration).putCombinePerson(combinePersonRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

