/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PersonResult } from '../model';
// @ts-ignore
import type { UpdatePersonRequest } from '../model';
/**
 * PersonUpdateControllerApi - axios parameter creator
 * @export
 */
export const PersonUpdateControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {UpdatePersonRequest} updatePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePerson: async (updatePersonRequest: UpdatePersonRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updatePersonRequest' is not null or undefined
            assertParamExists('updatePerson', 'updatePersonRequest', updatePersonRequest)
            const localVarPath = `/admin/update_person_details/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePersonRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PersonUpdateControllerApi - functional programming interface
 * @export
 */
export const PersonUpdateControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PersonUpdateControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {UpdatePersonRequest} updatePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePerson(updatePersonRequest: UpdatePersonRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePerson(updatePersonRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PersonUpdateControllerApi.updatePerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PersonUpdateControllerApi - factory interface
 * @export
 */
export const PersonUpdateControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PersonUpdateControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {UpdatePersonRequest} updatePersonRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePerson(updatePersonRequest: UpdatePersonRequest, options?: RawAxiosRequestConfig): AxiosPromise<PersonResult> {
            return localVarFp.updatePerson(updatePersonRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PersonUpdateControllerApi - object-oriented interface
 * @export
 * @class PersonUpdateControllerApi
 * @extends {BaseAPI}
 */
export class PersonUpdateControllerApi extends BaseAPI {
    /**
     * 
     * @param {UpdatePersonRequest} updatePersonRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PersonUpdateControllerApi
     */
    public updatePerson(updatePersonRequest: UpdatePersonRequest, options?: RawAxiosRequestConfig) {
        return PersonUpdateControllerApiFp(this.configuration).updatePerson(updatePersonRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

