/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SubjectRequest } from '../model';
// @ts-ignore
import type { SubjectsResult } from '../model';
/**
 * SubjectRemoveControllerApi - axios parameter creator
 * @export
 */
export const SubjectRemoveControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {SubjectRequest} subjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSubject: async (subjectRequest: SubjectRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subjectRequest' is not null or undefined
            assertParamExists('updateSubject', 'subjectRequest', subjectRequest)
            const localVarPath = `/admin/remove_subject/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subjectRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SubjectRemoveControllerApi - functional programming interface
 * @export
 */
export const SubjectRemoveControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SubjectRemoveControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {SubjectRequest} subjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSubject(subjectRequest: SubjectRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubjectsResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSubject(subjectRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubjectRemoveControllerApi.updateSubject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SubjectRemoveControllerApi - factory interface
 * @export
 */
export const SubjectRemoveControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SubjectRemoveControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {SubjectRequest} subjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSubject(subjectRequest: SubjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubjectsResult> {
            return localVarFp.updateSubject(subjectRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SubjectRemoveControllerApi - object-oriented interface
 * @export
 * @class SubjectRemoveControllerApi
 * @extends {BaseAPI}
 */
export class SubjectRemoveControllerApi extends BaseAPI {
    /**
     * 
     * @param {SubjectRequest} subjectRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubjectRemoveControllerApi
     */
    public updateSubject(subjectRequest: SubjectRequest, options?: RawAxiosRequestConfig) {
        return SubjectRemoveControllerApiFp(this.configuration).updateSubject(subjectRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

