/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { TextRequest } from '../model';
// @ts-ignore
import type { TextResult } from '../model';
/**
 * TextApi - axios parameter creator
 * @export
 */
export const TextApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {TextRequest} textRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getText: async (textRequest: TextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textRequest' is not null or undefined
            assertParamExists('getText', 'textRequest', textRequest)
            const localVarPath = `/getText/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(textRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TextApi - functional programming interface
 * @export
 */
export const TextApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TextApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {TextRequest} textRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getText(textRequest: TextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TextResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getText(textRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TextApi.getText']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TextApi - factory interface
 * @export
 */
export const TextApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TextApiFp(configuration)
    return {
        /**
         * 
         * @param {TextRequest} textRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getText(textRequest: TextRequest, options?: RawAxiosRequestConfig): AxiosPromise<TextResult> {
            return localVarFp.getText(textRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TextApi - object-oriented interface
 * @export
 * @class TextApi
 * @extends {BaseAPI}
 */
export class TextApi extends BaseAPI {
    /**
     * 
     * @param {TextRequest} textRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TextApi
     */
    public getText(textRequest: TextRequest, options?: RawAxiosRequestConfig) {
        return TextApiFp(this.configuration).getText(textRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

