/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CombinePersonRequest
 */
export interface CombinePersonRequest {
    /**
     * 
     * @type {number}
     * @memberof CombinePersonRequest
     */
    'id1'?: number;
    /**
     * 
     * @type {number}
     * @memberof CombinePersonRequest
     */
    'id2'?: number;
}

