/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EditLinkRequest
 */
export interface EditLinkRequest {
    /**
     * 
     * @type {number}
     * @memberof EditLinkRequest
     */
    'location_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof EditLinkRequest
     */
    'person_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof EditLinkRequest
     */
    'link_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof EditLinkRequest
     */
    'link_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditLinkRequest
     */
    'link_url'?: string;
}

