/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EditReferenceLinkRequest
 */
export interface EditReferenceLinkRequest {
    /**
     * 
     * @type {string}
     * @memberof EditReferenceLinkRequest
     */
    'type'?: string;
    /**
     * 
     * @type {number}
     * @memberof EditReferenceLinkRequest
     */
    'link_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof EditReferenceLinkRequest
     */
    'link_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditReferenceLinkRequest
     */
    'link_url'?: string;
}

