/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HomeTextRequest
 */
export interface HomeTextRequest {
    /**
     * 
     * @type {string}
     * @memberof HomeTextRequest
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof HomeTextRequest
     */
    'text_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof HomeTextRequest
     */
    'language'?: string;
}

