/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Collectie } from './collectie';
// May contain unused imports in some cases
// @ts-ignore
import type { MyLocation } from './my-location';
// May contain unused imports in some cases
// @ts-ignore
import type { Person } from './person';
// May contain unused imports in some cases
// @ts-ignore
import type { Text } from './text';

/**
 * 
 * @export
 * @interface Letter
 */
export interface Letter {
    /**
     * 
     * @type {number}
     * @memberof Letter
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Letter
     */
    'comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof Letter
     */
    'localDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof Letter
     */
    'number'?: number;
    /**
     * 
     * @type {Array<Person>}
     * @memberof Letter
     */
    'senders': Array<Person>;
    /**
     * 
     * @type {Array<Person>}
     * @memberof Letter
     */
    'recipients': Array<Person>;
    /**
     * 
     * @type {Array<MyLocation>}
     * @memberof Letter
     */
    'sender_locations': Array<MyLocation>;
    /**
     * 
     * @type {Array<MyLocation>}
     * @memberof Letter
     */
    'recipient_locations': Array<MyLocation>;
    /**
     * 
     * @type {string}
     * @memberof Letter
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof Letter
     */
    'remarks'?: string;
    /**
     * 
     * @type {Text}
     * @memberof Letter
     */
    'text'?: Text;
    /**
     * 
     * @type {Collectie}
     * @memberof Letter
     */
    'collectie'?: Collectie;
}

