/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LettersRequest
 */
export interface LettersRequest {
    /**
     * 
     * @type {number}
     * @memberof LettersRequest
     */
    'requestCode'?: number;
    /**
     * 
     * @type {number}
     * @memberof LettersRequest
     */
    'fromId'?: number;
    /**
     * 
     * @type {number}
     * @memberof LettersRequest
     */
    'toId'?: number;
}

