/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Letter } from './letter';

/**
 * 
 * @export
 * @interface LetterRequest
 */
export interface LetterRequest {
    /**
     * 
     * @type {number}
     * @memberof LetterRequest
     */
    'number'?: number;
    /**
     * 
     * @type {string}
     * @memberof LetterRequest
     */
    'comment'?: string;
    /**
     * 
     * @type {Letter}
     * @memberof LetterRequest
     */
    'letter'?: Letter;
    /**
     * 
     * @type {string}
     * @memberof LetterRequest
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof LetterRequest
     */
    'language'?: string;
}

