/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LocationUpdateRequest
 */
export interface LocationUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof LocationUpdateRequest
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof LocationUpdateRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof LocationUpdateRequest
     */
    'comment'?: string;
}

