/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Link } from './link';
// May contain unused imports in some cases
// @ts-ignore
import type { Text } from './text';

/**
 * 
 * @export
 * @interface MyLocation
 */
export interface MyLocation {
    /**
     * 
     * @type {string}
     * @memberof MyLocation
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof MyLocation
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof MyLocation
     */
    'location_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyLocation
     */
    'description'?: string;
    /**
     * 
     * @type {Array<Link>}
     * @memberof MyLocation
     */
    'links'?: Array<Link>;
    /**
     * 
     * @type {string}
     * @memberof MyLocation
     */
    'comment'?: string;
    /**
     * 
     * @type {Text}
     * @memberof MyLocation
     */
    'text'?: Text;
}

