/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageReference } from './page-reference';

/**
 * 
 * @export
 * @interface Page
 */
export interface Page {
    /**
     * 
     * @type {number}
     * @memberof Page
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    'chapter_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    'picture_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    'picture_caption'?: string;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    'page_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    'chapter_title'?: string;
    /**
     * 
     * @type {Array<PageReference>}
     * @memberof Page
     */
    'references'?: Array<PageReference>;
}

