/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PageReference
 */
export interface PageReference {
    /**
     * 
     * @type {number}
     * @memberof PageReference
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PageReference
     */
    'type'?: PageReferenceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PageReference
     */
    'key'?: string;
    /**
     * 
     * @type {string}
     * @memberof PageReference
     */
    'description'?: string;
}

export const PageReferenceTypeEnum = {
    Letter: 'LETTER',
    Person: 'PERSON',
    Location: 'LOCATION',
    Subject: 'SUBJECT',
    Link: 'LINK'
} as const;

export type PageReferenceTypeEnum = typeof PageReferenceTypeEnum[keyof typeof PageReferenceTypeEnum];


