/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PersonLettersRequest
 */
export interface PersonLettersRequest {
    /**
     * 
     * @type {number}
     * @memberof PersonLettersRequest
     */
    'requestCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof PersonLettersRequest
     */
    'toFrom'?: PersonLettersRequestToFromEnum;
    /**
     * 
     * @type {number}
     * @memberof PersonLettersRequest
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PersonLettersRequest
     */
    'orderBy'?: PersonLettersRequestOrderByEnum;
}

export const PersonLettersRequestToFromEnum = {
    To: 'TO',
    From: 'FROM'
} as const;

export type PersonLettersRequestToFromEnum = typeof PersonLettersRequestToFromEnum[keyof typeof PersonLettersRequestToFromEnum];
export const PersonLettersRequestOrderByEnum = {
    Date: 'DATE',
    Number: 'NUMBER',
    SenderLastname: 'SENDER_LASTNAME',
    SenderFirstname: 'SENDER_FIRSTNAME'
} as const;

export type PersonLettersRequestOrderByEnum = typeof PersonLettersRequestOrderByEnum[keyof typeof PersonLettersRequestOrderByEnum];


