/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubjectRequest
 */
export interface SubjectRequest {
    /**
     * 
     * @type {number}
     * @memberof SubjectRequest
     */
    'subject_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SubjectRequest
     */
    'subject_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectRequest
     */
    'language'?: string;
}

