/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Text } from './text';

/**
 * 
 * @export
 * @interface TextRequest
 */
export interface TextRequest {
    /**
     * 
     * @type {number}
     * @memberof TextRequest
     */
    'id'?: number;
    /**
     * 
     * @type {Text}
     * @memberof TextRequest
     */
    'text'?: Text;
    /**
     * 
     * @type {string}
     * @memberof TextRequest
     */
    'language'?: string;
    /**
     * 
     * @type {string}
     * @memberof TextRequest
     */
    'text_string'?: string;
    /**
     * 
     * @type {string}
     * @memberof TextRequest
     */
    'title_string'?: string;
    /**
     * 
     * @type {number}
     * @memberof TextRequest
     */
    'text_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof TextRequest
     */
    'person_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof TextRequest
     */
    'location_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof TextRequest
     */
    'letter_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof TextRequest
     */
    'subject_id'?: number;
}

