/*
 * Copyright (c) 2028 - 2025, Zaphod Consulting BV, Christine Karman
 * This project is free software: you can redistribute it and/or modify it under the terms of
 * the Apache License, Version 2.0. You can find a copy of the license at
 * http://www.apache.org/licenses/LICENSE-2.0.
 */
import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
    nl: {
        about: "About",
        titel: "Het nichtje van tante Thérèse",
        home: "Home",
        letters: "Brieven",
        people: "Personen",
        locations: "Locaties",
        references: "Referenties",
        topics: "Topics",
        admin: "Admin",
        login: "Login",
        logout: "Logout",
        pages: "Verhaal",
        op_nummer: "Op nummer",
        op_datum: "Op datum",
        naar_nummer: "Ga naar nummer",
        search: "Zoek",
        previous: "Vorige",
        next: "Volgende",
        op_voornaam: "Op voornaam",
        op_achternaam: "Op achternaam",
        geboren: "Geboren",
        overleden: "Overleden",
        brieven_van: "Brieven ",
        meer: "Meer",
        nummer: "Nummer",
        to: "Aan",
        from: "Van",
        date: "Datum",
        chapter: "Hoofdstuk",
        page: "Pagina",
        content: "Inhoud",
        sender: "Afzender",
        recipient: "Ontvanger",
        location: "Plaats",
        remarks: "Opmerkingen",
        help_title: "Navigatie",
        help: "Op de brieven pagina, klik op een briefnummer of naam voor meer info. Verder kun je meestal op een naam klikken voor meer info.Op de verhaal pagina, blader met de pijltjes bovenaan.",
        location_name: "Locatie name",
        back: "Terug",
        ok: "OK",
        uit: "uit",
        aboutText: "Deze website is een project van Zaphod Consulting BV, Christine Karman. De content is licensed volgens de Apache License, Versie 2.0.",
        more_about_site: "Meer over de site",
        siteVersion: "Site Versie",
        aboutChristine: "About Christine",
        name: "Naam",
        comment: "Opmerkingen",
        personLettersText: "Brieven",
        locationLettersText: "Brieven van en naar ",
        delete: "Delete",
        edit: "Edit",
        password: "Password",
        username: "Username",
        addLetter: "Brief toevoegen",
        addLocation: "Locatie toevoegen",
        indexLetters: "Indexeer brieven",
        addPerson: "Persoon toevoegen",
        text: "Tekst",
        locationId: "Locatie Id",
        personId: "Persoon Id",
        senderLocation: "Afzender locatie",
        recipientLocation: "Ontvanger locatie",
        submit: "Submit",
        cancel: "Cancel",
        update: "Update",
        preview: "Preview",
        letterNumber: "Briefnummer",
        letterRemoved: "Brief verwijderd",
        addPageReferenceTitle: "Add Page Reference",
        niet_doen: "Niet doen",
        combineren: "Combineren",
        close: "Sluiten",
        dutch: "Nederlands",
        english: "English",
        german: "Deutsch",
        spanish: "Español",
        french: "Français",
        selectLanguage: "Taal",
        nickname: "Voornaam",
        fullname: "Full name",
        tussenvoegsel: "Tussenvoegsel",
        lastname: "Achternaam",
        plaats: "Plaats",
        opmerkingen: "Opmerkingen",
        image_url: "Image URL",
        image_caption: "Image Caption",
        addTopic: "Onderwerp toevoegen",
        linknaam: "Link naam",
        link_url: "Link URL",
        translateLetter: "Vertaal brief",
    },
    en: {
        about: "About",
        titel: "Aunt Thérèse's niece",
        home: "Home",
        letters: "Letters",
        people: "People",
        locations: "Locations",
        references: "References",
        topics: "Topics",
        admin: "Admin",
        login: "Login",
        logout: "Logout",
        pages: "Story",
        op_nummer: "By number",
        op_datum: "By date",
        naar_nummer: "Go to number",
        search: "Search",
        previous: "Previous",
        next: "Next",
        op_voornaam: "By first name",
        op_achternaam: "By last name",
        geboren: "Birth date",
        overleden: "Deceased",
        brieven_van: "Letters ",
        meer: "More",
        nummer: "Number",
        to: "To",
        from: "From",
        date: "Date",
        chapter: "Chapter",
        page: "Page",
        content: "Content",
        sender: "Sender",
        recipient: "Recipient",
        location: "Location",
        remarks: "Remarks",
        help_title: "Navigation",
        help: "On the letters page, click on a letter number or a name for info. In the letter pages, you can click on any name to navigate. On the story page, browse with the arrows at the top of the page.",
        location_name: "Location name",
        back: "Back",
        ok: "OK",
        uit: "from",
        aboutText: "This website is a project of Zaphod Consulting BV, Christine Karman. The content is licensed under the Apache License, Version 2.0.",
        more_about_site: "More about the site",
        siteVersion: "Site Version",
        aboutChristine: "About Christine",
        name: "Name",
        comment: "Comments",
        personLettersText: "Letters",
        locationLettersText: "Letters to and from",
        delete: "Delete",
        edit: "Edit",
        password: "Password",
        username: "Username",
        addLetter: "Add letter",
        addLocation: "Add location",
        indexLetters: "Index letters",
        addPerson: "Add person",
        text: "Text",
        locationId: "Location Id",
        personId: "Person Id",
        senderLocation: "Sender location",
        recipientLocation: "Ontvanger locatie",
        submit: "Submit",
        cancel: "Cancel",
        update: "Update",
        preview: "Preview",
        letterNumber: "Letter number",
        letterRemoved: "Brief verwijderd",
        addPageReferenceTitle: "Add Page Reference",
        editCommentLine: "Edit commentaarregel",
        editsenderRecipient: "Edit",
        deleteLetter: "Delete brief",
        collection: "Collectie",
        editText: "Edit tekst",
        niet_doen: "Don't",
        combineren: "Combine",
        close: "Close",
        dutch: "Nederlands",
        english: "English",
        german: "Deutsch",
        spanish: "Español",
        french: "Français",
        selectLanguage: "Language",
        nickname: "First ",
        fullname: "Full name",
        tussenvoegsel: "Infix",
        lastname: "Last name",
        plaats: "City",
        opmerkingen: "Comments",
        image_url: "Image URL",
        image_caption: "Image Caption",
        addTopic: "Add topic",
        linknaam: "Link name",
        linktitle: "Link title",
        linktext: "Link text",
        link_url: "Link URL",
        translateLetter: "Translate letter",
    },
    fr: {
        about: "À propos",
        titel: "La nièce de tante Thérèse",
        home: "Accueil",
        letters: "Lettres",
        people: "Personnes",
        locations: "Lieux",
        references: "Références",
        topics: "Sujets",
        admin: "Administration",
        login: "Connexion",
        logout: "Déconnexion",
        pages: "Histoire",
        op_nummer: "Par numéro",
        op_datum: "Par date",
        naar_nummer: "Aller au numéro",
        search: "Rechercher",
        previous: "Précédent",
        next: "Suivant",
        op_voornaam: "Par prénom",
        op_achternaam: "Par nom",
        geboren: "Né(e)",
        overleden: "Décédé(e)",
        brieven_van: "Lettres de",
        meer: "Plus",
        nummer: "Numéro",
        to: "À",
        from: "De",
        date: "Date",
        chapter: "Chapitre",
        page: "Page",
        content: "Contenu",
        sender: "Expéditeur",
        recipient: "Destinataire",
        location: "Lieu",
        remarks: "Remarques",
        help_title: "Navigation",
        help: "Sur la page des lettres, cliquez sur un numéro de lettre ou un nom pour plus d'informations. Vous pouvez généralement cliquer sur un nom pour plus d'informations. Sur la page de l'histoire, naviguez avec les flèches en haut.",
        location_name: "Nom du lieu",
        back: "Retour",
        ok: "OK",
        uit: "de",
        aboutText: "Ce site web est un projet de Zaphod Consulting BV, Christine Karman. Le contenu est sous licence Apache License, Version 2.0.",
        more_about_site: "En savoir plus sur le site",
        siteVersion: "Version du site",
        aboutChristine: "À propos de Christine",
        name: "Nom",
        comment: "Commentaires",
        personLettersText: "Lettres",
        locationLettersText: "Lettres de et vers",
        delete: "Supprimer",
        edit: "Modifier",
        password: "Mot de passe",
        username: "Nom d'utilisateur",
        addLetter: "Ajouter une lettre",
        addLocation: "Ajouter un lieu",
        indexLetters: "Indexer les lettres",
        addPerson: "Ajouter une personne",
        text: "Texte",
        locationId: "ID du lieu",
        personId: "ID de la personne",
        senderLocation: "Lieu de l'expéditeur",
        recipientLocation: "Lieu du destinataire",
        submit: "Envoyer",
        cancel: "Annuler",
        update: "Mettre à jour",
        preview: "Aperçu",
        letterNumber: "Numéro de lettre",
        letterRemoved: "Lettre supprimée",
        addPageReferenceTitle: "Ajouter une référence de page",
        niet_doen: "Ne pas faire",
        combineren: "Combiner",
        close: "Fermer",
        dutch: "Néerlandais",
        english: "Anglais",
        german: "Allemand",
        spanish: "Espagnol",
        french: "Français",
        selectLanguage: "Langue",
        nickname: "Prénom",
        fullname: "Nom complet",
        tussenvoegsel: "Tussenvoegsel",
        lastname: "Nom",
        lieu: "Lieu",
        commentaires: "Commentaires",
        image_url: "Image URL",
        image_caption: "Image Caption",
        addTopic: "Ajouter un sujet",
        linknaam: "Link name",
        linktitle: "Link title",
        linktext: "Link text",
        translateLetter: "Traduire la lettre",
    },
    de: {
        about: "Über",
        titel: "Die Nichte von Tante Thérèse",
        home: "Startseite",
        letters: "Briefe",
        people: "Personen",
        locations: "Orte",
        references: "Referenzen",
        topics: "Themen",
        admin: "Admin",
        login: "Anmelden",
        logout: "Abmelden",
        pages: "Geschichte",
        op_nummer: "Nach Nummer",
        op_datum: "Nach Datum",
        naar_nummer: "Gehe zu Nummer",
        search: "Suche",
        previous: "Vorherige",
        next: "Nächste",
        op_voornaam: "Nach Vorname",
        op_achternaam: "Nach Nachname",
        geboren: "Geboren",
        overleden: "Verstorben",
        brieven_van: "Briefe ",
        meer: "Mehr",
        nummer: "Nummer",
        to: "An",
        from: "Von",
        date: "Datum",
        chapter: "Kapitel",
        page: "Seite",
        content: "Inhalt",
        sender: "Absender",
        recipient: "Empfänger",
        location: "Ort",
        remarks: "Anmerkungen",
        help_title: "Navigation",
        help: "Auf der Briefeseite klicken Sie auf eine Briefnummer oder einen Namen für weitere Informationen. Sie können meist auch auf einen Namen klicken für weitere Details. Auf der Geschichteseite blättern Sie mit den Pfeilen oben.",
        location_name: "Ortsname",
        back: "Zurück",
        ok: "OK",
        uit: "aus",
        aboutText: "Diese Website ist ein Projekt von Zaphod Consulting BV, Christine Karman. Der Inhalt ist unter der Apache-Lizenz, Version 2.0 lizenziert.",
        more_about_site: "Mehr über die Website",
        siteVersion: "Website-Version",
        aboutChristine: "Über Christine",
        name: "Name",
        comment: "Anmerkungen",
        personLettersText: "Briefe",
        locationLettersText: "Briefe von und nach ",
        delete: "Löschen",
        edit: "Bearbeiten",
        password: "Passwort",
        username: "Benutzername",
        addLetter: "Brief hinzufügen",
        addLocation: "Ort hinzufügen",
        indexLetters: "Briefe indexieren",
        addPerson: "Person hinzufügen",
        text: "Text",
        locationId: "Orts-ID",
        personId: "Personen-ID",
        senderLocation: "Absenderort",
        recipientLocation: "Empfängerort",
        submit: "Absenden",
        cancel: "Abbrechen",
        update: "Aktualisieren",
        preview: "Vorschau",
        letterNumber: "Briefnummer",
        letterRemoved: "Brief entfernt",
        addPageReferenceTitle: "Seitenreferenz hinzufügen",
        niet_doen: "Nicht machen",
        combineren: "Kombinieren",
        close: "Schließen",
        dutch: "Niederländisch",
        english: "Englisch",
        german: "Deutsch",
        spanish: "Spanisch",
        french: "Französisch",
        selectLanguage: "Sprache",
        nickname: "Vorname",
        fullname: "Vollständiger Name",
        tussenvoegsel: "Namenszusatz",
        lastname: "Nachname",
        plaats: "Ort",
        opmerkingen: "Anmerkungen",
        image_url: "Bild-URL",
        image_caption: "Bildunterschrift",
        addTopic: "Thema hinzufügen",
        linknaam: "Link-Name",
        linktitle: "Link-Titel",
        linktext: "Link-Text",
        link_url: "Link-URL",
        translateLetter: "Brief übersetzen",
    },
    es: {
        about: "Acerca de",
        titel: "La sobrina de tía Thérèse",
        home: "Inicio",
        letters: "Cartas",
        people: "Personas",
        locations: "Ubicaciones",
        references: "Referencias",
        topics: "Temas",
        admin: "Administrador",
        login: "Iniciar sesión",
        logout: "Cerrar sesión",
        pages: "Historia",
        op_nummer: "Por número",
        op_datum: "Por fecha",
        naar_nummer: "Ir al número",
        search: "Buscar",
        previous: "Anterior",
        next: "Siguiente",
        op_voornaam: "Por nombre",
        op_achternaam: "Por apellido",
        geboren: "Nacido",
        overleden: "Fallecido",
        brieven_van: "Cartas ",
        meer: "Más",
        nummer: "Número",
        to: "Para",
        from: "De",
        date: "Fecha",
        chapter: "Capítulo",
        page: "Página",
        content: "Contenido",
        sender: "Remitente",
        recipient: "Destinatario",
        location: "Ubicación",
        remarks: "Observaciones",
        help_title: "Navegación",
        help: "En la página de cartas, haga clic en un número de carta o nombre para más información. También puede hacer clic en un nombre para más información. En la página de historia, use las flechas en la parte superior.",
        location_name: "Nombre de ubicación",
        back: "Volver",
        ok: "Aceptar",
        uit: "de",
        aboutText: "Este sitio web es un proyecto de Zaphod Consulting BV, Christine Karman. El contenido está licenciado bajo la Licencia Apache, Versión 2.0.",
        more_about_site: "Más sobre el sitio",
        siteVersion: "Versión del sitio",
        aboutChristine: "Sobre Christine",
        name: "Nombre",
        comment: "Comentarios",
        personLettersText: "Cartas",
        locationLettersText: "Cartas de y para ",
        delete: "Eliminar",
        edit: "Editar",
        password: "Contraseña",
        username: "Usuario",
        addLetter: "Agregar carta",
        addLocation: "Agregar ubicación",
        indexLetters: "Indexar cartas",
        addPerson: "Agregar persona",
        text: "Texto",
        locationId: "ID de ubicación",
        personId: "ID de persona",
        senderLocation: "Ubicación del remitente",
        recipientLocation: "Ubicación del destinatario",
        submit: "Enviar",
        cancel: "Cancelar",
        update: "Actualizar",
        preview: "Vista previa",
        letterNumber: "Número de carta",
        letterRemoved: "Carta eliminada",
        addPageReferenceTitle: "Agregar referencia de página",
        niet_doen: "No hacer",
        combineren: "Combinar",
        close: "Cerrar",
        dutch: "Neerlandés",
        english: "Inglés",
        german: "Alemán",
        spanish: "Español",
        french: "Francés",
        selectLanguage: "Idioma",
        nickname: "Apodo",
        fullname: "Nombre completo",
        tussenvoegsel: "Prefijo",
        lastname: "Apellido",
        plaats: "Lugar",
        opmerkingen: "Comentarios",
        image_url: "URL de imagen",
        image_caption: "Pie de foto",
        addTopic: "Agregar tema",
        linknaam: "Nombre del enlace",
        linktitle: "Título del enlace",
        linktext: "Texto del enlace",
        link_url: "URL del enlace",
        translateLetter: "Traducir carta",
    }
});
export default strings;
