/*
 * Copyright (c) 2018 - 2024, Zaphod Consulting BV, Christine Karman
 * This project is free software: you can redistribute it and/or modify it under the terms of
 * the Apache License, Version 2.0. You can find a copy of the license at
 * http://www.apache.org/licenses/LICENSE-2.0.
 */
import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
    nl: {
        about: "About",
        titel: "Het nichtje van tante Thérèse",
        home: "Home",
        letters: "Brieven",
        people: "Personen",
        locations: "Locaties",
        references: "Referenties",
        topics: "Topics",
        admin: "Admin",
        login: "Login",
        logout: "Logout",
        pages: "Verhaal",
        op_nummer: "Op nummer",
        op_datum: "Op datum",
        naar_nummer: "Ga naar nummer",
        search: "Zoek",
        previous: "Vorige",
        next: "Volgende",
        op_voornaam: "Op voornaam",
        op_achternaam: "Op achternaam",
        geboren: "Geboren",
        overleden: "Overleden",
        brieven_van: "Brieven ",
        meer: "Meer",
        nummer: "Nummer",
        to: "Aan",
        from: "Van",
        date: "Datum",
        chapter: "Hoofdstuk",
        page: "Pagina",
        content: "Inhoud",
        sender: "Afzender",
        recipient: "Ontvanger",
        location: "Plaats",
        remarks: "Opmerkingen",
        help_title: "Navigatie",
        help: "Op de brieven pagina, klik op een briefnummer of naam voor meer info. Verder kun je meestal op een naam klikken voor meer info.Op de verhaal pagina, blader met de pijltjes bovenaan.",
        location_name: "Locatie name",
        back: "Terug",
        ok: "OK",
        uit: "uit",
        aboutText: "Deze website is een project van Zaphod Consulting BV, Christine Karman. De content is licensed volgens de Apache License, Versie 2.0.",
        more_about_site: "Meer over de site",
        siteVersion: "Site Versie",
        aboutChristine: "About Christine",
        name: "Naam",
        comment: "Opmerkingen",
        personLettersText: "Brieven",
        locationLettersText: "Brieven van en naar ",
        delete: "Delete",
        edit: "Edit",
        password: "Password",
        username: "Username",
        addLetter: "Brief toevoegen",
        addLocation: "Locatie toevoegen",
        indexLetters: "Indexeer brieven",
        addPerson: "Persoon toevoegen",
        text: "Tekst",
        locationId: "Locatie Id",
        personId: "Persoon Id",
        senderLocation: "Afzender locatie",
        recipientLocation: "Ontvanger locatie",
        submit: "Submit",
        cancel: "Cancel",
        update: "Update",
        preview: "Preview",
        letterNumber: "Briefnummer",
        letterRemoved: "Brief verwijderd",
        addPageReferenceTitle: "Add Page Reference",
        niet_doen: "Niet doen",
        combineren: "Combineren",
        close: "Sluiten"
    },
    en: {
        about: "About",
        titel: "Aunt Thérèse's niece",
        home: "Home",
        letters: "Letters",
        people: "People",
        locations: "Locations",
        references: "References",
        topics: "Topics",
        admin: "Admin",
        login: "Login",
        logout: "Logout",
        pages: "Story",
        op_nummer: "By number",
        op_datum: "By date",
        naar_nummer: "Go to number",
        search: "Search",
        previous: "Previous",
        next: "Next",
        op_voornaam: "By first name",
        op_achternaam: "By last name",
        geboren: "Birth date",
        overleden: "Deceased",
        brieven_van: "Letters ",
        meer: "More",
        nummer: "Number",
        to: "To",
        from: "From",
        date: "Date",
        chapter: "Chapter",
        page: "Page",
        content: "Content",
        sender: "Sender",
        recipient: "Recipient",
        location: "Location",
        remarks: "Remarks",
        help_title: "Navigation",
        help: "On the letters page, click on a letter number or a name for info. In the letter pages, you can click on any name to navigate. On the story page, browse with the arrows at the top of the page.",
        location_name: "Location name",
        back: "Back",
        ok: "OK",
        uit: "from",
        aboutText: "This website is a project of Zaphod Consulting BV, Christine Karman. The content is licensed under the Apache License, Version 2.0.",
        more_about_site: "Meer over de site",
        siteVersion: "Site Version",
        aboutChristine: "About Christine",
        name: "Name",
        comment: "Comments",
        personLettersText: "Letters",
        locationLettersText: "Letters to and from",
        delete: "Delete",
        edit: "Edit",
        password: "Password",
        username: "Username",
        addLetter: "Add letter",
        addLocation: "Add location",
        indexLetters: "Index letters",
        addPerson: "Add person",
        text: "Text",
        locationId: "Location Id",
        personId: "Person Id",
        senderLocation: "Sender location",
        submit: "Submit",
        cancel: "Cancel",
        update: "Update",
        preview: "Preview",
        letterNumber: "Letter number",
        editCommentLine: "Edit commentaarregel",
        editsenderRecipient: "Edit afzender/ontvanger",
        deleteLetter: "Delete brief",
        collection: "Collectie",
        editText: "Edit tekst",
        niet_doen: "Don't",
        combineren: "Combine",
        close: "Close",
    },
    fr: {
        about: "À propos",
        titel: "La nièce de tante Thérèse",
        home: "Accueil",
        letters: "Lettres",
        people: "Personnes",
        locations: "Lieux",
        references: "Références",
        topics: "Sujets",
        admin: "Admin",
        login: "Connexion",
        logout: "Déconnexion",
        pages: "Histoire",
        op_nummer: "Par numéro",
        op_datum: "Par date",
        naar_nummer: "Aller au numéro",
        search: "Rechercher",
        previous: "Précédent",
        next: "Suivant",
        op_voornaam: "Par prénom",
        op_achternaam: "Par nom",
        geboren: "Né(e)",
        overleden: "Décédé(e)",
        brieven_van: "Lettres ",
        meer: "Plus",
        nummer: "Numéro",
        to: "À",
        from: "De",
        date: "Date",
        chapter: "Chapitre",
        page: "Page",
        content: "Contenu",
        sender: "Expéditeur",
        recipient: "Destinataire",
        location: "Lieu",
        remarks: "Remarques",
        help_title: "Navigation",
        help: "Sur la page des lettres, cliquez sur un numéro de lettre ou un nom pour plus d'informations. Vous pouvez généralement cliquer sur un nom pour plus d'informations. Sur la page de l'histoire, utilisez les flèches en haut pour naviguer.",
        location_name: "Nom du lieu",
        back: "Retour",
        ok: "OK",
        uit: "de",
        aboutText: "Ce site web est un projet de Zaphod Consulting BV, Christine Karman. Le contenu est sous licence Apache License, Version 2.0.",
        more_about_site: "En savoir plus sur le site",
        siteVersion: "Version du site",
        aboutChristine: "À propos de Christine",
        name: "Nom",
        comment: "Commentaires",
        personLettersText: "Lettres",
        locationLettersText: "Lettres de et vers ",
        delete: "Supprimer",
        edit: "Modifier",
        password: "Mot de passe",
        username: "Nom d'utilisateur",
        addLetter: "Ajouter une lettre",
        addLocation: "Ajouter un lieu",
        indexLetters: "Indexer les lettres",
        addPerson: "Ajouter une personne",
        text: "Texte",
        locationId: "ID du lieu",
        personId: "ID de la personne",
        senderLocation: "Lieu de l'expéditeur",
        recipientLocation: "Lieu du destinataire",
        submit: "Soumettre",
        cancel: "Annuler",
        update: "Mettre à jour",
        preview: "Aperçu",
        letterNumber: "Numéro de lettre",
        letterRemoved: "Lettre supprimée",
        addPageReferenceTitle: "Ajouter une référence de page"
    },
    de: {
        titel: "Tante Thérèses Nichte",
        home: "Startsite",
        letters: "Briefe",
        about: "Uber uns",
        people: "Personen",
        locations: "Orte",
        references: "Referenzen",
        topics: "Topics",
        admin: "Admin",
        login: "Login",
        logout: "Logout",
        pages: "Geschichte",
        op_nummer: "Nach Nummer",
        op_datum: "Nach Datum",
        naar_nummer: "Gehe zu Nummer",
        search: "Suchen",
        previous: "Vorherige",
        next: "Nächste",
        op_voornaam: "Nach Vorname",
        op_achternaam: "Nach Nachnamen",
        geboren: "Geburtsdatum",
        overleden: "Verstorben",
        brieven_van: "Briefe ",
        brieven_aan: "Briefe nach",
        meer: "Mehr",
        nummer: "Nummer",
        to: "An",
        from: "Von",
        date: "Datum",
        chapter: "Kapitel",
        page: "Seite",
        content: "Inhalt",
        sender: "Absender",
        recipient: "Empfanger",
        location: "Ort",
        remarks: "Bemerkungen",
        help_title: "Navigieren",
        help: "Klicken Sie auf der Briefe Liste auf eine Briefnummer oder einen Namen, um Informationen zu erhalten. Auf den Briefseiten können Sie auf einen beliebigen Namen klicken, um zu navigieren.",
        location_name: "Location name",
        back: "Zurück",
        ok: "OK",
        uit: "aus",
        aboutText: "This website is a project of Zaphod Consulting BV, Christine Karman. The content is licensed under the Apache License, Version 2.0.",
        more_about_site: "Mehr über die site",
        siteVersion: "Site-Version",
        aboutChristine: "About Christine",
        name: "Name",
        comment: "Kommentare",
        personLettersText: "Briefe",
        locationLettersText: "Briefe von und nach ",
        delete: "Löschen",
        edit: "Bearbeiten",
        password: "Passwort",
        username: "Benutzername",
        addLetter: "Brief hinzufügen",
        addLocation: "Standort hinzufügen",
        indexLetters: "Briefe indexieren",
        addPerson: "Person hinzufügen",
        text: "Text",
        locationId: "Standort-ID",
        personId: "Personen-ID",
        senderLocation: "Absenderstandort",
        recipientLocation: "Empfängerstandort",
        submit: "Absenden",
        cancel: "Abbrechen",
        update: "Aktualisieren",
        preview: "Vorschau",
        letterNumber: "Briefnummer",
        letterRemoved: "Brief gelöscht",
        addPageReferenceTitle: "Seitenreferenz hinzufügen"
    },
    es: {
        about: "Acerca de",
        titel: "La sobrina de la tía Thérèse",
        home: "Inicio",
        letters: "Cartas",
        people: "Personas",
        locations: "Ubicaciones",
        references: "Referencias",
        topics: "Temas",
        admin: "Administrador",
        login: "Iniciar sesión",
        logout: "Cerrar sesión",
        pages: "Historia",
        op_nummer: "Por número",
        op_datum: "Por fecha",
        naar_nummer: "Ir al número",
        search: "Buscar",
        previous: "Anterior",
        next: "Siguiente",
        op_voornaam: "Por nombre",
        op_achternaam: "Por apellido",
        geboren: "Nacimiento",
        overleden: "Fallecimiento",
        brieven_van: "Cartas ",
        brieven_aan: "Cartas para",
        meer: "Más",
        nummer: "Número",
        to: "Para",
        from: "De",
        date: "Fecha",
        chapter: "Capítulo",
        page: "Página",
        content: "Contenido",
        sender: "Remitente",
        recipient: "Destinatario",
        location: "Ubicación",
        remarks: "Observaciones",
        help_title: "Navegación",
        help: "En la página de cartas, haga clic en un número de carta o nombre para más información. También puede hacer clic en un nombre para más detalles. En la página de historia, use las flechas en la parte superior para navegar.",
        location_name: "Nombre de ubicación",
        back: "Volver",
        ok: "Aceptar",
        uit: "de",
        aboutText: "Este sitio web es un proyecto de Zaphod Consulting BV, Christine Karman. El contenido está licenciado bajo Apache License, Versión 2.0.",
        more_about_site: "Más sobre el sitio",
        siteVersion: "Versión del sitio",
        aboutChristine: "Sobre Christine",
        name: "Nombre",
        comment: "Comentarios",
        personLettersText: "Cartas",
        locationLettersText: "Cartas de y para ",
        delete: "Eliminar",
        edit: "Editar",
        password: "Contraseña",
        username: "Usuario",
        addLetter: "Agregar carta",
        addLocation: "Agregar ubicación",
        indexLetters: "Indexar cartas",
        addPerson: "Agregar persona",
        text: "Texto",
        locationId: "ID de ubicación",
        personId: "ID de persona",
        senderLocation: "Ubicación del remitente",
        recipientLocation: "Ubicación del destinatario",
        submit: "Enviar",
        cancel: "Cancelar",
        update: "Actualizar",
        preview: "Vista previa",
        letterNumber: "Número de carta",
        letterRemoved: "Carta eliminada",
        addPageReferenceTitle: "Agregar referencia de página"
    }
});
export default strings;
